[app]
    logLevel              = "warn"
[monitor]
    interval              = "20s"
    healthCheckSql        = "SHOW SCHEMAS FROM hive"
[gateway]
    ports                 = [8080, 8081, 8082, 8083, 8084, 8085, 8086, 8087, 8088, 8089, 8090]
